# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: l:/FPGA_Projects/02_KintexBoard_Playground/01_uart_to_usb/01_uart_to_usb.srcs/sources_1/ip/uart_pll/uart_pll.xci
# IP: The module: 'uart_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: l:/FPGA_Projects/02_KintexBoard_Playground/01_uart_to_usb/01_uart_to_usb.gen/sources_1/ip/uart_pll/uart_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_pll'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: l:/FPGA_Projects/02_KintexBoard_Playground/01_uart_to_usb/01_uart_to_usb.gen/sources_1/ip/uart_pll/uart_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: l:/FPGA_Projects/02_KintexBoard_Playground/01_uart_to_usb/01_uart_to_usb.gen/sources_1/ip/uart_pll/uart_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: l:/FPGA_Projects/02_KintexBoard_Playground/01_uart_to_usb/01_uart_to_usb.srcs/sources_1/ip/uart_pll/uart_pll.xci
# IP: The module: 'uart_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: l:/FPGA_Projects/02_KintexBoard_Playground/01_uart_to_usb/01_uart_to_usb.gen/sources_1/ip/uart_pll/uart_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: l:/FPGA_Projects/02_KintexBoard_Playground/01_uart_to_usb/01_uart_to_usb.gen/sources_1/ip/uart_pll/uart_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: l:/FPGA_Projects/02_KintexBoard_Playground/01_uart_to_usb/01_uart_to_usb.gen/sources_1/ip/uart_pll/uart_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
